# Generated by Django 4.2.18 on 2025-06-09 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.TextField()),
                ("content", models.TextField()),
                ("receivers", models.JSONField(default=list)),
                ("sender", models.JSONField(default=list)),
                ("system_generated", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("failed", "Failed"),
                            ("sent", "Sent"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Email",
                "verbose_name_plural": "Scheduled Emails",
            },
        ),
    ]
