# Generated by Django 4.2.18 on 2025-07-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower values are higher priority.'),
        ),
    ]
