# Generated by Django 4.2.18 on 2025-07-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0004_menu_menuimage'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_beach',
            field=models.ForeignKey(blank=True, help_text='The beach this staff user manages. Null for non-staff or admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='beach.beach'),
        ),
    ]
