runtime: python311
entrypoint: gunicorn -b :$PORT goldbrella.wsgi:application

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  DJANGO_SETTINGS_MODULE: "goldbrella.settings"
  DEBUG: "False"

handlers:
  - url: /static
    static_dir: static/
    secure: always

  - url: /media
    static_dir: media/
    secure: always

  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup

beta_settings:
  cloud_sql_instances: "PROJECT_ID:REGION:INSTANCE_NAME" 