# Generated by Django 4.2.18 on 2025-04-30 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(default=uuid.uuid4, max_length=150),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Card"),
                            ("cash", "Cash"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="booking.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Payment",
                "verbose_name_plural": "Booking Payments",
            },
        ),
        migrations.AddConstraint(
            model_name="bookingpayment",
            constraint=models.UniqueConstraint(
                fields=("booking", "transaction_id"),
                name="unique_booking_payment_transaction",
            ),
        ),
    ]
