# Generated by Django 4.2.18 on 2025-06-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingpayment",
            name="updated",
        ),
    ]
