# Generated by Django 4.2.18 on 2025-06-09 16:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zone", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sunbed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sunbed_type",
                    models.CharField(
                        choices=[("standard", "Standard"), ("vip", "VIP")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("area", models.CharField(max_length=20)),
                ("identity", models.CharField(blank=True, max_length=8)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("uncleaned", "Uncleaned"),
                            ("occupied", "Occupied"),
                            ("broken", "Broken"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunbeds",
                        to="zone.zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sunbed",
                "verbose_name_plural": "Sunbeds",
            },
        ),
        migrations.AddConstraint(
            model_name="sunbed",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("area"),
                django.db.models.functions.text.Upper("identity"),
                models.F("zone"),
                name="unique_sunbed_per_zone",
            ),
        ),
    ]
