# Generated by Django 4.2.18 on 2025-04-28 20:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beach", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sunbed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sunbed_type",
                    models.CharField(
                        choices=[("standard", "Standard"), ("vip", "VIP")],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("area", models.CharField(max_length=20)),
                ("identity", models.CharField(max_length=5)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "beach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunbeds",
                        to="beach.beach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sunbed",
                "verbose_name_plural": "Sunbeds",
            },
        ),
        migrations.AddConstraint(
            model_name="sunbed",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("area"),
                django.db.models.functions.text.Upper("identity"),
                models.F("beach"),
                name="unique_sunbed_per_beach",
            ),
        ),
    ]
