# Generated by Django 4.2.18 on 2025-07-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunbed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunbed',
            name='column',
            field=models.PositiveIntegerField(blank=True, help_text='Column number for visual placement', null=True),
        ),
        migrations.AddField(
            model_name='sunbed',
            name='row',
            field=models.PositiveIntegerField(blank=True, help_text='Row number for visual placement', null=True),
        ),
    ]
