# Generated by Django 4.2.18 on 2025-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sunbed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sunbed",
            name="identity",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
