# Generated by Django 4.2.18 on 2025-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("partial_reserved", "Partial Reserved"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("reserved", "Reserved"),
                ],
                default="reserved",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("partial_reserved", "Partial Reserved"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("reserved", "Reserved"),
                ],
                default="reserved",
                max_length=20,
            ),
        ),
    ]
