# Generated by Django 4.2.18 on 2025-07-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Cocktails', 'Cocktails'), ('Beer', 'Beer'), ('Wine', 'Wine'), ('Non-Alcoholic', 'Non-Alcoholic'), ('Food', 'Food'), ('Other', 'Other')], default='Other', max_length=32),
        ),
    ]
