# Generated by Django 4.2.18 on 2025-06-09 16:55

import beach.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True, related_name="beaches", to="services.facility"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beaches",
                        to="location.location",
                    ),
                ),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True, related_name="beaches", to="services.rule"
                    ),
                ),
            ],
            options={
                "verbose_name": "Beach",
                "verbose_name_plural": "Beaches",
            },
        ),
        migrations.CreateModel(
            name="BeachOpeningSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("opening_date", models.DateField()),
                ("closing_date", models.DateField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "beach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="beach.beach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beach Opening Season",
                "verbose_name_plural": "Beach Opening Seasons",
            },
        ),
        migrations.CreateModel(
            name="BeachOpeningHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="beach.beachopeningseason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beach Opening Time",
                "verbose_name_plural": "Beach Opening Times",
            },
        ),
        migrations.CreateModel(
            name="BeachImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=beach.helpers.beach_image_filepath),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "beach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="beach.beach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beach Image",
                "verbose_name_plural": "Beach Images",
            },
        ),
        migrations.AddConstraint(
            model_name="beachopeningseason",
            constraint=models.UniqueConstraint(
                fields=("beach", "opening_date", "closing_date"),
                name="unique_opening_season",
            ),
        ),
        migrations.AddConstraint(
            model_name="beachopeninghour",
            constraint=models.UniqueConstraint(
                fields=("season", "weekday"), name="unique_opening_per_season"
            ),
        ),
        migrations.AddConstraint(
            model_name="beach",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude", "location"),
                name="unique_beach_per_location",
            ),
        ),
    ]
