# Generated by Django 4.2.18 on 2025-05-30 14:46

import beach.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beach", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beachimage",
            name="image",
            field=models.ImageField(upload_to=beach.helpers.beach_image_filepath),
        ),
    ]
