# Generated by Django 4.2.18 on 2025-07-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0002_beach_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for QR or direct access', max_length=32, null=True, unique=True),
        ),
    ]
