# Generated by Django 4.2.18 on 2025-07-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0004_menu_menuimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='columns',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sunbed columns', null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='rows',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sunbed rows', null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='total_sunbeds',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of sunbeds for this beach', null=True),
        ),
    ]
