# Generated by Django 4.2.18 on 2025-07-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beach', '0005_beach_columns_beach_rows_beach_total_sunbeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beach',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='beach',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='beach',
            name='total_sunbeds',
        ),
    ]
