# Generated by Django 4.2.18 on 2025-06-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_bookinginvoice_currency_bookinginvoice_tax_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookinginvoice",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="historicalbookinginvoice",
            name="tax_amount",
        ),
    ]
