# Generated by Django 4.2.18 on 2025-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_remove_bookinginvoice_tax_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookinginvoice",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="bookinginvoice",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="historicalbookinginvoice",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="historicalbookinginvoice",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="bookinginvoice",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookinginvoice",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbookinginvoice",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalbookinginvoice",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
