# Generated by Django 4.2.18 on 2025-06-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_remove_bookinginvoice_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinginvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("refunded", "Refunded"),
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbookinginvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("refunded", "Refunded"),
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
