name: gcloud-deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    # 1) Check out your code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2) Install & authenticate gcloud
    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # 3) Deploy code using gcloud
    - name: Deploy to GCE via SSH
      run: |
        gcloud compute ssh --zone ${{ secrets.GCP_ZONE }} \
          ${{ secrets.GCE_USER }}@${{ secrets.GCE_INSTANCE }} \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --command="cd ~/goldbrella-backend && sh deployer.sh"
