name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/runner
          chmod 600 ~/.ssh/runner

      - name: Deploy to GCE via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/runner "${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_HOST }}" << 'EOF'
            cd "${{ secrets.GCP_DEPLOY_PATH }}"
            git -C "${{ secrets.GCP_DEPLOY_PATH }}" pull
            sh deploy.sh
          EOF
