name: gcloud-deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    # 1) Check out your code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2) Authenticate to GCP
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3) Install & configure gcloud
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # 3.5) Debug the gcloud
    - name: Debug gcloud & OS Login
      run: |
        echo "Active account: $(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
        gcloud compute os-login describe-profile \
          --account=$(gcloud auth list --filter=status:ACTIVE --format='value(account)')

    # 4) Now you have an “active” account—SSH will work
    - name: Deploy to GCE via SSH
      run: |
        gcloud compute ssh \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --zone ${{ secrets.GCP_ZONE }} \
          ${{ secrets.GCE_USER }}@${{ secrets.GCE_INSTANCE }} \
          --command="cd ~/goldbrella-backend && sh deployer.sh"
