name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "MKDIR RUN SUCCESS"
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/runner
          echo "KEY GEN SUCCESS"
          chmod 600 ~/.ssh/runner
          echo "CHMOD RUN SUCCESS"
          ssh-keyscan -H "${{ secrets.GCP_VM_HOST }}" >> ~/.ssh/known_hosts
          echo "KEYSCAN RUN SUCCESS"

      - name: Deploy to GCE via SSH
        run: |
          ssh "${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_HOST }}" << 'EOF'
            cd "${{ secrets.GCP_DEPLOY_PATH }}"
            sh deployer.sh
          EOF
